name: Python Continuous Integration

on: [ push ]

jobs:
  test_branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - uses: abatilo/actions-poetry@v2.1.3
      - run: poetry run isort .
      - run: poetry run black .
      - run: poetry run flake8 .
      - run: poetry run mypy .
      - run: poetry run pytest --cov=python_template
